//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortalDBDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Company
    {
        public System.Guid TFId { get; set; }
        public System.Guid TFContact_Id { get; set; }
        public System.Guid TFCompany_Id { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
