//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortalDBDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inbox
    {
        public System.Guid TFId { get; set; }
        public string TFMessage { get; set; }
        public string TFSenderNumber { get; set; }
        public System.Guid TFSim_Id { get; set; }
        public System.DateTime TFDateTime { get; set; }
        public string TFDateTimeFA { get; set; }
        public bool TFIsRead { get; set; }
    
        public virtual SIM SIM { get; set; }
    }
}
