//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortalDBDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Queue()
        {
            this.SendBoxes = new HashSet<SendBox>();
            this.Queue_Phone = new HashSet<Queue_Phone>();
        }
    
        public System.Guid TFId { get; set; }
        public System.Guid TFMessage_Id { get; set; }
        public System.DateTime TFDateTimeCreate { get; set; }
        public string TFDateTimeCreateFA { get; set; }
        public System.DateTime TFDateTimeRequest { get; set; }
        public string TFDateTimeRequestFA { get; set; }
        public int TFScheduleType { get; set; }
        public System.Guid TFUser_Id { get; set; }
        public bool TFEnable { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SendBox> SendBoxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Queue_Phone> Queue_Phone { get; set; }
    }
}
