//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortalDBDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue_Phone
    {
        public System.Guid TFId { get; set; }
        public System.Guid TFQueue_Id { get; set; }
        public System.Guid TFPhone_Id { get; set; }
        public bool TFIsUnderProcess { get; set; }
        public bool TFEnable { get; set; }
        public bool TFActive { get; set; }
        public bool TFError { get; set; }
    
        public virtual Phone Phone { get; set; }
        public virtual Queue Queue { get; set; }
    }
}
