//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortalDBDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendBox_Phone
    {
        public System.Guid TFId { get; set; }
        public System.Guid TFSendBox_Id { get; set; }
        public System.Guid TFPhone_Id { get; set; }
        public System.Guid TFSim_Id { get; set; }
        public System.DateTime TFDateTimeSend { get; set; }
        public string TFDateTimeSendFA { get; set; }
        public Nullable<int> TFGSM_Id { get; set; }
        public bool TFIsDelivered { get; set; }
        public Nullable<System.DateTime> TFDateTimeSendGSM { get; set; }
        public string TFDateTimeSendGSMFA { get; set; }
        public Nullable<System.DateTime> TFDateTimeDelivery { get; set; }
        public string TFDateTimeDeliveryFA { get; set; }
    
        public virtual Phone Phone { get; set; }
        public virtual SendBox SendBox { get; set; }
        public virtual SIM SIM { get; set; }
    }
}
