//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortalDBDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIM_User
    {
        public System.Guid TFId { get; set; }
        public System.Guid TFSIM_Id { get; set; }
        public System.Guid TFUser_Id { get; set; }
        public Nullable<int> TFMax { get; set; }
    
        public virtual SIM SIM { get; set; }
        public virtual User User { get; set; }
    }
}
