//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortalDBDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class USSD
    {
        public System.Guid TFId { get; set; }
        public System.Guid TFSim_Id { get; set; }
        public string TFSend { get; set; }
        public string TFReceive { get; set; }
        public System.DateTime TFDTSend { get; set; }
        public string TFDTSendFa { get; set; }
        public bool TFIsPrefred { get; set; }
        public string TFPreferdTitle { get; set; }
        public bool TFIsSent { get; set; }
    
        public virtual SIM SIM { get; set; }
    }
}
