//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortalWebPanel.SMSPortalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSPortalService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddToQueue", ReplyAction="http://tempuri.org/IUserService/AddToQueueResponse")]
        void AddToQueue(string userName, string password, string content, string[] numbers, SMSPortalCross.Enums.Schedule ScheduleType, System.DateTime dtSend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddToQueue", ReplyAction="http://tempuri.org/IUserService/AddToQueueResponse")]
        System.Threading.Tasks.Task AddToQueueAsync(string userName, string password, string content, string[] numbers, SMSPortalCross.Enums.Schedule ScheduleType, System.DateTime dtSend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddRangeToQueue", ReplyAction="http://tempuri.org/IUserService/AddRangeToQueueResponse")]
        void AddRangeToQueue(string userName, string password, string content, long start, long finish, SMSPortalCross.Enums.Schedule ScheduleType, System.DateTime dtSend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddRangeToQueue", ReplyAction="http://tempuri.org/IUserService/AddRangeToQueueResponse")]
        System.Threading.Tasks.Task AddRangeToQueueAsync(string userName, string password, string content, long start, long finish, SMSPortalCross.Enums.Schedule ScheduleType, System.DateTime dtSend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ProccessScheduleQueue", ReplyAction="http://tempuri.org/IUserService/ProccessScheduleQueueResponse")]
        void ProccessScheduleQueue(System.Guid userId, System.Guid sendBoxId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ProccessScheduleQueue", ReplyAction="http://tempuri.org/IUserService/ProccessScheduleQueueResponse")]
        System.Threading.Tasks.Task ProccessScheduleQueueAsync(System.Guid userId, System.Guid sendBoxId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : SMSPortalWebPanel.SMSPortalService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<SMSPortalWebPanel.SMSPortalService.IUserService>, SMSPortalWebPanel.SMSPortalService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddToQueue(string userName, string password, string content, string[] numbers, SMSPortalCross.Enums.Schedule ScheduleType, System.DateTime dtSend) {
            base.Channel.AddToQueue(userName, password, content, numbers, ScheduleType, dtSend);
        }
        
        public System.Threading.Tasks.Task AddToQueueAsync(string userName, string password, string content, string[] numbers, SMSPortalCross.Enums.Schedule ScheduleType, System.DateTime dtSend) {
            return base.Channel.AddToQueueAsync(userName, password, content, numbers, ScheduleType, dtSend);
        }
        
        public void AddRangeToQueue(string userName, string password, string content, long start, long finish, SMSPortalCross.Enums.Schedule ScheduleType, System.DateTime dtSend) {
            base.Channel.AddRangeToQueue(userName, password, content, start, finish, ScheduleType, dtSend);
        }
        
        public System.Threading.Tasks.Task AddRangeToQueueAsync(string userName, string password, string content, long start, long finish, SMSPortalCross.Enums.Schedule ScheduleType, System.DateTime dtSend) {
            return base.Channel.AddRangeToQueueAsync(userName, password, content, start, finish, ScheduleType, dtSend);
        }
        
        public void ProccessScheduleQueue(System.Guid userId, System.Guid sendBoxId) {
            base.Channel.ProccessScheduleQueue(userId, sendBoxId);
        }
        
        public System.Threading.Tasks.Task ProccessScheduleQueueAsync(System.Guid userId, System.Guid sendBoxId) {
            return base.Channel.ProccessScheduleQueueAsync(userId, sendBoxId);
        }
    }
}
